### ISSUE TITLE
makedirs_exist_ok cannot be imported from torchvision

### ISSUE THREAD

**Issue by ghost** [mfinzi/LieConv#4]
With torchvision version '0.8.1+cu101' and torch version '1.7.0+cu101' I get the error 

ImportError: cannot import name 'makedir_exist_ok' from 'torchvision.datasets.utils' 

Indeed a search in torchvision github return no results for makedir_exist_ok.

I manually changed makedir_exist_ok to os.makedirs (for Python 3.7) in lie_conv/datasets.py and it worked, but posting here for reference

**Comment by mfinzi** [comment]
Hi Diane,
It looks the function [makedir_exist_ok](https://github.com/pytorch/vision/blob/build/v0.4.1/torchvision/datasets/utils.py#L45) was removed in the newer version of torchvision. Thanks for letting us know and we'll update the codebase.
